#!/bin/bash
# Script that sanitizes the output generated by Regenerator
sed -i "s/ASL $/ASL A/g" rambo-0334-fff9.asm
sed -i "s/ROL $/ROL A/g" rambo-0334-fff9.asm
sed -i "s/ROR $/ROR A/g" rambo-0334-fff9.asm
sed -i "s/LSR $/LSR A/g" rambo-0334-fff9.asm
sed -i "s/LSL $/LSL A/g" rambo-0334-fff9.asm

